name: Django CI

on:
  pull_request:
    branches:
      - main  # Change to the branch you want PRs to target (e.g., 'main', 'develop')

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This action checks out the code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the version of Python to use (make sure it matches your environment)

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Set up the database (optional)
      run: |
        python manage.py migrate  # Apply migrations

    - name: Run tests
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        python manage.py test  # Run Django tests
