name: Django CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main  # Ensure PRs target the correct branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your local Python version

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Set up the database (if using PostgreSQL)
      run: |
        python manage.py migrate  # Apply migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres  # Change if needed

    - name: Run tests with pytest
      run: |
        source venv/bin/activate  # Ensure virtual environment is active
        pytest  # Run Pytest for Django tests
