name: Django CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image

    services:
      postgres:
        image: postgres:13  # You can specify the version you need here
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # Use Python 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run database migrations
      run: |
        python manage.py migrate  # Apply migrations if needed

    - name: Run tests
      run: |
        pytest --disable-warnings  # Run tests using pytest
